project:
  type: website

website:
  title: "IS415-GAA-JinYuan&WanShen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Proposal/Proposal.qmd
        text: Proposal

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

