project:
  type: website

website:
  title: "IS415-GAA-JinYuan&WanShen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Proposal/Proposal.qmd
        text: Proposal
      - href: dataPreProcess.qmd
        text: Data Pre-Processing
      - href: userGuide.qmd
        text: User-Guide
      - href: poster.qmd
        text: Poster
      - href: https://recyclewatch.shinyapps.io/recyclesgshiny/
        text: Shiny App

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

