---
title: "KDE Analysis"
---

```{r}
pacman::p_load(sf, tidyverse, tmap, maptools, raster, spatstat, spNetwork, classInt, viridis, arrow)
```

```{r}
binlocation <- read_rds("../Data/alba/ewbins.rds")
mpsz <- st_read(dsn = "testdata", layer = "MPSZ-2019")
mpsz <- st_transform(mpsz, crs = 3414)
```

```{r}
tmap_mode("plot")
tm_shape(binlocation) +
  tm_dots()
```

```{r}
tmap_options(check.and.fix = TRUE)
tm_shape(mpsz) +
  tm_polygons() +
tm_shape(binlocation) +
  tm_dots()
```

```{r}
bin_sf <- as_Spatial(binlocation)
bin_sp <- as(bin_sf, "SpatialPoints")
bin_ppp <- as(bin_sp, "ppp")
plot(bin_ppp)
```

```{r}
island <- as_Spatial(mpsz)
island_sp <- as(island, "SpatialPolygons")
sg_owin <- as(island_sp, "owin")
plot(sg_owin)
```

```{r}
islandSG_ppp_bin = bin_ppp[sg_owin]
```

```{r}
kde_bin_bw <- density(bin_ppp,
                              sigma=bw.diggle,
                              edge=TRUE,
                            kernel="gaussian") 
```

```{r}
plot(kde_bin_bw)
```

```{r}
bw1 <- bw.diggle(bin_ppp)
bw1
```

```{r}
bin_ppp.km <- rescale(bin_ppp, 1000, "km")
```

```{r}
kde_bin.bw <- density(bin_ppp.km, sigma=bw.diggle, edge=TRUE, kernel="gaussian")
plot(kde_bin.bw)
```

```{r}
gridded_kde_bin_bw <- as.SpatialGridDataFrame.im(kde_bin.bw)
spplot(gridded_kde_bin_bw)
```

```{r}
kde_kde_bin_bw_raster <- raster(gridded_kde_bin_bw)
```

```{r}
projection(kde_kde_bin_bw_raster) <- CRS("+init=EPSG:3414")
kde_kde_bin_bw_raster
```

```{r}
tmap_mode("plot")
tm_shape(kde_kde_bin_bw_raster) +
  tm_raster(style = "cont", palette = "plasma") +
  tm_layout(legend.show = TRUE, legend.text.color = "white")
```

```{r}
pung <- mpsz %>%
  filter(PLN_AREA_N == "PUNGGOL")
pung <- pung%>%
  st_union()
pung <- st_make_valid(pung)

tamp <- mpsz %>%
  filter(PLN_AREA_N == "TAMPINES")
tamp <- tamp%>%
  st_union()
tamp <- st_make_valid(tamp)

cck <- mpsz %>%
  filter(PLN_AREA_N == "CHOA CHU KANG")
cck <- cck%>%
  st_union()
cck <- st_make_valid(cck)

jw <- mpsz %>%
  filter(PLN_AREA_N == "JURONG WEST")
jw <- jw%>%
  st_union()
jw <- st_make_valid(jw)

pung <- st_transform(pung, crs = 3414)
tamp <- st_transform(tamp, crs = 3414)
cck <- st_transform(cck, crs = 3414)
jw <- st_transform(jw, crs = 3414)
```

```{r}
roads_in_singapore <- read_rds("testdata/sgRoad.rds")
pung_roads <- st_intersection(roads_in_singapore, pung)
tamp_roads <- st_intersection(roads_in_singapore, tamp)
cck_roads <- st_intersection(roads_in_singapore, cck)
jw_roads <- st_intersection(roads_in_singapore, jw)
```

```{r}
par(mfrow=c(2,2))
plot(pung, main = "Punggol")
plot(tamp, main = "Tampines")
plot(cck, main = "Choa Chu Kang")
plot(jw, main = "Jurong West")
```

```{r}
tmap_mode('plot')
tmap_arrange(tm_shape(pung_roads) +
               tm_lines(col = "red") +
               tm_layout(title = "Punggol", title.size = 0.8),
             tm_shape(tamp_roads) +
               tm_lines(col = "blue") +
               tm_layout(title = "Tampines", title.size = 0.8), 
             tm_shape(cck_roads) +
               tm_lines(col = "green") +
               tm_layout(title = "Choa Chu Kang", title.size = 0.8),
             tm_shape(jw_roads) +
               tm_lines(col = "orange") +
               tm_layout(title = "Jurong West", title.size = 0.8),
             asp=2, ncol=2)
```

```{r}
# Identify POINTs
pung_points <- pung_roads[st_geometry_type(pung_roads) != "POINT", ]
tamp_points <- tamp_roads[st_geometry_type(tamp_roads) != "POINT", ]
cck_points <- cck_roads[st_geometry_type(cck_roads) != "POINT", ]
jw_points <- jw_roads[st_geometry_type(jw_roads) != "POINT", ]
```

```{r}
pung_roads <- st_cast(pung_points, "LINESTRING")
tamp_roads <- st_cast(tamp_points, "LINESTRING")
cck_roads <- st_cast(cck_points, "LINESTRING")
jw_roads <- st_cast(jw_points, "LINESTRING")
```

```{r}
lixels_pung <- lixelize_lines(pung_roads, 
                         700, 
                         mindist = 350)
lixels_tamp <- lixelize_lines(tamp_roads, 
                         700, 
                         mindist = 350)
lixels_cck <- lixelize_lines(cck_roads, 
                         700, 
                         mindist = 350)
lixels_jw <- lixelize_lines(jw_roads, 
                         700, 
                         mindist = 350)
```

```{r}
samples_pung <- lines_center(lixels_pung)
samples_tamp <- lines_center(lixels_tamp)
samples_cck <- lines_center(lixels_cck)
samples_jw <- lines_center(lixels_jw)
```

```{r}
origin_pung = st_intersection(binlocation, pung)
origin_tamp = st_intersection(binlocation, tamp)
origin_cck = st_intersection(binlocation, cck)
origin_jw = st_intersection(binlocation, jw)
```

```{r}
tmap_mode('plot')
tm_basemap("OpenStreetMap") +
tm_shape(pung_roads) +
  tm_lines(col = "red") +
  tm_shape(origin_pung) + 
  tm_dots()
tmap_mode('plot')
```

```{r}
tmap_mode('plot')
tm_basemap("OpenStreetMap") +
tm_shape(tamp_roads) +
  tm_lines(col = "blue") +
  tm_shape(origin_tamp) + 
  tm_dots()
tmap_mode('plot')
```

```{r}
tmap_mode('view')
tm_basemap("OpenStreetMap") +
tm_shape(cck_roads) +
  tm_lines(col = "green") +
  tm_shape(origin_cck) + 
  tm_dots()
tmap_mode('plot')
```

```{r}
tmap_mode('plot')
tm_basemap("OpenStreetMap") +
tm_shape(jw_roads) +
  tm_lines(col = "orange") +
  tm_shape(origin_jw) + 
  tm_dots()
tmap_mode('plot')
```
